deadlines:
  '3':
    Wed:
      date: 2026/01/21 11:00am EST 
      content: ip1
  '4':
    Wed:
      date: 2026/01/28 11:00am EST 
      content: tp1
  '5':
    Wed:
      date: 2026/02/04 11:00am EST
      content: ip2
  '6':
    Wed:
      date: 2026/02/11 11:00am EST
      content: tp2
  '7':
    Wed:
      date: 2026/02/18 11:00am EST
      content: ip3
  '8':
    Wed:
      date: 2026/02/25 11:00am EST
      content: tp3
  '14':
    Wed:
      date: 2026/04/10 6:00pm EST
      content: tp4
  '16':
    Wed:
      date: 2026/04/20 11:00am EST
      content: tp5
dates:
  firstMonday: 2026/01/05
  numWeeks: 16
types:
  default:
    className: lesson
  holiday:
    className: holiday