deadlines:
  '3':
    Wed:
      date: 2026/01/21 12:00pm 
      content: ip1
  '4':
    Wed:
      date: 2026/01/28 12:00pm 
      content: tp1
  '5':
    Wed:
      date: 2026/02/04 12:00pm
      content: ip2
  '6':
    Wed:
      date: 2026/02/11 12:00pm
      content: tp2
  '7':
    Wed:
      date: 2026/02/18 12:00pm
      content: ip3
  '8':
    Wed:
      date: 2026/02/25 12:00pm
      content: tp3
  '14':
    Wed:
      date: 2026/04/10 6:00pm
      content: tp4
  '16':
    Wed:
      date: 2026/04/20 12:00pm
      content: tp5
dates:
  firstMonday: 2026/01/05
  numWeeks: 16
types:
  default:
    className: lesson
  holiday:
    className: holiday